title: Brian Hurst

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

exclude:
  - assets/css
  - assets/js
  - Gemfile*
  - node_modules
  - package*.json
  - tailwind.js
  - vendor
  - webpack.config.js

keep_files:
  - assets/css
  - assets/js
