version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4-node-browsers
    steps:
      - checkout
      - run: npm install
      - run: bundle install
      - run: webpack -p
      - run: bundle exec jekyll build
      - run: echo 'bhurst.me' > ./_site/CNAME
      - deploy:
          name: deploy
          command: |
            if [ "${CIRCLE_BRANCH}" = "src" ]; then
              gh-pages -b master -d _site
            fi
